const TOKEN_LIMITS = {
  MAX_TOKENS_PER_BATCH: 8000,
  MAX_OUTPUT_TOKENS_PER_BATCH: 8000,
  MAX_OUTPUT_TOKENS_OVERALL: 2000,
  AVERAGE_CHARS_PER_TOKEN: 3,
};

const REQUEST_INPUT_INTRO_MESSAGE = {
  COMMIT_ANALYSIS_REQUEST:
    "아래 커밋 JSON을 빠짐없이 위 지침과 스키마에 맞춰 분석",
  OVERALL_ANALYSIS_REQUEST:
    "아래 커밋 분석 결과 추출 JSON을 빠짐없이 위 지침과 스키마에 맞춰 분석",
};

const OPENAI_MODEL = "gpt-4o-mini";

export { TOKEN_LIMITS, OPENAI_MODEL, REQUEST_INPUT_INTRO_MESSAGE };
