const TOKEN_LIMITS = {
  MAX_TOKENS_PER_BATCH: 6000,
  MAX_OUTPUT_TOKENS_PER_BATCH: 10000,
  AVERAGE_CHARS_PER_TOKEN: 3,
  MAX_OUTPUT_TOKENS_OVERALL: 2000,
};

const REQUEST_INPUT_INTRO_MESSAGE = {
  COMMIT_ANALYSIS_REQUEST:
    "아래 커밋 JSON을 빠짐없이 위 지침과 스키마에 맞춰 분석",
  OVERALL_ANALYSIS_REQUEST:
    "아래 커밋 분석 결과 추출 JSON을 빠짐없이 위 지침과 스키마에 맞춰 분석",
};

export { TOKEN_LIMITS, REQUEST_INPUT_INTRO_MESSAGE };
