const MAX_TOKENS_PER_BATCH = 8000;
const AVERAGE_CHARS_PER_TOKEN = 3;
const OPENAI_MODEL = "gpt-4o-mini";
const MAX_OUTPUT_TOKENS = 12000;

export {
  MAX_TOKENS_PER_BATCH,
  AVERAGE_CHARS_PER_TOKEN,
  OPENAI_MODEL,
  MAX_OUTPUT_TOKENS,
};
